    services:
        mariadb:
            image: mariadb
            container_name: mariadb
            build: ./requirements/mariadb
            restart: unless-stopped
            environment:
                WORDPRESS_DB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
                WORDPRESS_DB_ROOT_PASSWORD_FILE: /run/secrets/DB_ROOT_PASSWORD
            env_file: .env
            secrets:
                - DB_PASSWORD
                - DB_ROOT_PASSWORD
            networks:
                - inception_bridge
            volumes:
                - db_data:/var/lib/mysql
            expose:
                - "3306"
        wordpress:
            image: wordpress
            container_name: wordpress
            build: ./requirements/wordpress
            restart: unless-stopped
            environment:
                WORDPRESS_DB_HOST: ${DB_HOSTNAME}
                WORDPRESS_DB_USER: ${WP_DB_USER}
                WORDPRESS_DB_NAME: ${WP_DB_NAME}
                WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/WP_ADMIN_PASSWORD
                WORDPRESS_DB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
            env_file: .env
            secrets:
                - DB_PASSWORD
                - WP_ADMIN_PASSWORD
            depends_on:
                mariadb:
                    condition: service_started
            networks:
                - inception_bridge
            expose:
                - "9000"
            volumes:
                - wordpress_data:/var/www/html
        nginx:
            image: nginx
            container_name: nginx
            networks:
                - inception_bridge
            ports:
                - "443:443"
            build: ./requirements/nginx
            restart: unless-stopped
            env_file: .env
            depends_on:
                wordpress:
                    condition: service_started
            volumes:
                - wordpress_data:/var/www/html
    secrets:
        DB_PASSWORD:
            file: ../secrets/db_password.txt
        DB_ROOT_PASSWORD:
            file: ../secrets/db_root_password.txt
        WP_ADMIN_PASSWORD:
            file: ../secrets/wp_admin_password.txt
    volumes:
        db_data:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: ${DATA_FOLDER}/mariadb
        wordpress_data:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: ${DATA_FOLDER}/wordpress
    networks:
        inception_bridge:
          driver: bridge
