# server {
# 	listen 80;
# 	server_name ibenne.42.fr;
# 	root /var/www/html/;
# 	index index.php;

# 	# resolver 127.0.0.11 valid=10s;
# 	# resolver_timeout 5s;
# 	access_log /var/log/nginx/example.com-access.log;
# 	error_log  /var/log/nginx/example.com-error.log;

# 	location / {
# 		try_files $uri $uri/ /index.php?$query_string;
# 	}

# 	location ~ .php$ {
# 		include /etc/nginx/fastcgi_params;
# 		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
# 		fastcgi_param QUERY_STRING    $query_string;
# 		fastcgi_pass wordpress:9000;
# 	}

# 	location ~ /\.ht {
# 		deny all;
# 	}
# }

server {
    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;
    server_name localhost;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate     /etc/ssl/certs/ibenne.crt;
    ssl_certificate_key /etc/ssl/private/ibenne.key;

	add_header Strict-Transport-Security "max-age=63072000" always;

	ssl_stapling on;
    ssl_stapling_verify on;

    root /var/www/html;
    index index.php;

    access_log /var/log/nginx/example.com-access.log;
    error_log  /var/log/nginx/example.com-error.log;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	location ~ \.php$ {
		include /etc/nginx/fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param QUERY_STRING    $query_string;
		fastcgi_pass wordpress:9000;
	}

	location ~ /\.ht {
		deny all;
	}
}
